apiVersion: v1
kind: ServiceAccount
metadata:
  name: stellar-service-account
  labels:
    app: stellar

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stellar-service-account-role
  labels:
    app: stellar
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    verbs: ["create", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stellar-service-account-rolebinding
subjects:
  - kind: ServiceAccount
    name: stellar-service-account
roleRef:
  kind: Role
  name: stellar-service-account-role
  apiGroup: rbac.authorization.k8s.io