# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: certauth
commonLabels:
  app: stellar
  serviceName: stellar-web
resources:
  - "storage.yaml"
  - "deployment.yaml"
  - "service.yaml"
  - "ingress.yaml"