# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: certauth
namePrefix: celestialsovereign-
commonLabels:
  app: stellar
  stellar-ca-name: celestialsovereign
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: stellar-configmap
    files:
      - "stellar-config.yaml"
resources:
  - "service-account.yaml"
  - "storage.yaml"
  - "deployment.yaml"
  - "ingress.yaml"
  - "service.yaml"